[package]
name = "polyphonic"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
default-run = "polyphonic"

[dependencies]
blake3 = "1"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
tonic = { version = "0.12", optional = true }
prost = { version = "0.13", optional = true }
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "sync", "time"], optional = true }
wasmtime = { version = "34", default-features = false, features = ["cranelift", "runtime", "wat"], optional = true }
tokio-stream = { version = "0.1.19", default-features = false, features = ["sync"], optional = true }

[build-dependencies]
tonic-build = { version = "0.12", optional = true }

[features]
grpc = ["dep:tonic", "dep:prost", "dep:tokio", "dep:tonic-build", "dep:tokio-stream"]
wasm = ["dep:wasmtime"]

[[bin]]
name = "polyphonic"
path = "src/main.rs"

[[bin]]
name = "rpcbench"
path = "src/bin/rpcbench.rs"
required-features = ["grpc"]

[profile.release]
debug = true
lto = "thin"
codegen-units = 1

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"
missing_debug_implementations = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
undocumented_unsafe_blocks = "warn"
todo = "warn"
cast_precision_loss = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
